using System;
using System.Collections.Generic;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using System.Windows.Threading;
using ClassroomToolkit.App.Ink;
using ClassroomToolkit.App.Paint.Brushes;
using ClassroomToolkit.App.Presentation;
using ClassroomToolkit.App.Photos;
using ClassroomToolkit.App.Session;
using ClassroomToolkit.App.Utilities;
using ClassroomToolkit.App.Windowing;
using ClassroomToolkit.Services.Presentation;
using Microsoft.Extensions.Logging;
using MediaBrush = System.Windows.Media.Brush;
using MediaBrushes = System.Windows.Media.Brushes;
using MediaColor = System.Windows.Media.Color;
using WpfImage = System.Windows.Controls.Image;
using WpfPoint = System.Windows.Point;
using WpfRectangle = System.Windows.Shapes.Rectangle;

namespace ClassroomToolkit.App.Paint;

public partial class PaintOverlayWindow : Window
{
    private const int GwlStyle = -16;
    private const int GwlExstyle = -20;
    private const int WsExTransparent = 0x20;
    private const int WsExNoActivate = 0x08000000;

    private const uint MonitorDefaultToNearest = 2;
    private const uint SwpNoZorder = 0x0004;
    private const uint SwpNoActivate = 0x0010;
    private const uint SwpShowWindow = 0x0040;

    private const int PresentationFocusMonitorIntervalMs = PresentationRuntimeDefaults.FocusMonitorIntervalMs;
    private const int PresentationFocusCooldownMs = PresentationRuntimeDefaults.FocusRestoreCooldownMs;
    private const int CrossPageUpdateMinIntervalMs = CrossPageRuntimeDefaults.UpdateMinIntervalMs;
    private const double PhotoWheelZoomBaseDefault = PhotoZoomInputDefaults.WheelZoomBaseDefault;
    private const double PhotoKeyZoomStep = 1.06;
    private const double PhotoGestureZoomNoiseThreshold = PhotoZoomInputDefaults.GestureZoomNoiseThreshold;
    private const double PhotoZoomMinEventFactor = PhotoZoomInputDefaults.ZoomMinEventFactor;
    private const double PhotoZoomMaxEventFactor = PhotoZoomInputDefaults.ZoomMaxEventFactor;
    private const int PhotoWheelSuppressAfterGestureMs = PhotoTransformTimingDefaults.WheelSuppressAfterGestureMs;
    private const int PhotoZoomInteractionWindowMs = PhotoTransformTimingDefaults.ZoomInteractionWindowMs;
    private const int PhotoRenderQualityRestoreDelayMs = PhotoTransformTimingDefaults.RenderQualityRestoreDelayMs;
    private const int WpsNavDebounceMs = PresentationRuntimeDefaults.WpsNavDebounceMs;
    private const double PdfDefaultDpi = PhotoDocumentRuntimeDefaults.PdfDefaultDpi;
    private const int PdfCacheLimit = PhotoDocumentRuntimeDefaults.PdfCacheLimit;
    private const int NeighborPageCacheLimit = PhotoDocumentRuntimeDefaults.NeighborPageCacheLimit;

    private IntPtr _hwnd;
    private bool _inputPassthroughEnabled;
    private bool _focusBlocked;
    private bool? _lastAppliedInputPassthroughEnabled;
    private bool? _lastAppliedFocusBlocked;
    private bool _forcePresentationForegroundOnFullscreen;
    private bool _presentationClassifierAutoLearnEnabled;
    private readonly DispatcherTimer _presentationFocusMonitor;
    private readonly DispatcherTimer _photoRenderQualityRestoreTimer;
    private DateTime _nextPresentationFocusAttempt = PresentationRuntimeDefaults.UnsetTimestampUtc;
    private readonly uint _currentProcessId = (uint)Environment.ProcessId;

    private PaintToolMode _mode = PaintToolMode.Brush;
    private PaintShapeType _shapeType = PaintShapeType.Line;
    private bool _isDrawingShape;
    private WpfPoint _shapeStart;
    private Shape? _activeShape;
    private bool _triangleFirstEdgeCommitted;
    private bool _triangleAnchorSet;
    private WpfPoint _trianglePoint1;
    private WpfPoint _trianglePoint2;
    private bool _isRegionSelecting;
    private WpfPoint _regionStart;
    private WpfRectangle? _regionRect;
    private readonly ClassroomToolkit.Services.Presentation.PresentationControlService _presentationService;
    private readonly ClassroomToolkit.Services.Presentation.PresentationControlOptions _presentationOptions;
    private readonly PresentationInputPipeline _presentationInputPipeline;
    private readonly IOverlayPresentationTargetSnapshotProvider _presentationTargetSnapshotProvider;
    private readonly OverlayPresentationDispatchCoordinator _presentationDispatchCoordinator;
    private PresentationClassifier _presentationClassifier;
    private readonly Win32PresentationResolver _presentationResolver;
    private readonly WpsSlideshowNavigationHook? _wpsNavHook;
    private readonly IWpsNavHookClient? _wpsNavHookClient;
    private readonly WpsHookOrchestrator _wpsHookOrchestrator = new();
    private readonly IWpsHookUnavailableNotifier _wpsHookUnavailableNotifier = new MessageBoxWpsHookUnavailableNotifier();
    private readonly LatestOnlyAsyncGate _wpsNavHookStateGate = new();
    private bool _wpsNavHookActive;
    private bool _wpsHookInterceptKeyboard = true;
    private bool _wpsHookInterceptWheel = true;
    private bool _wpsHookBlockOnly;
    private int _wpsHookUnavailableNotifiedState;
    private DateTime _wpsNavBlockUntil = PresentationRuntimeDefaults.UnsetTimestampUtc;
    private (int Code, IntPtr Target, DateTime Timestamp)? _lastWpsNavEvent;
    private DateTime _lastWpsHookInput = PresentationRuntimeDefaults.UnsetTimestampUtc;
    private readonly List<RasterSnapshot> _history = new();

    private WpfPoint? _lastPointerPosition;
    private DateTime _lastPhotoGestureInputUtc = PhotoInputConflictDefaults.UnsetTimestampUtc;
    private DateTime _lastPhotoZoomInputUtc = PhotoInputConflictDefaults.UnsetTimestampUtc;
    private bool _presentationFocusRestoreEnabled = true;
    private readonly RefreshOrchestrator _refreshOrchestrator;
    private readonly PerfStats _perfMonitor;
    private readonly PerfStats _perfSavePage;
    private readonly PerfStats _perfLoadPage;
    private readonly PerfStats _perfRedrawSurface;
    private readonly PerfStats _perfEnsureSurface;
    private readonly PerfStats _perfClearSurface;
    private readonly PerfStats _perfApplyStrokes;

    private bool _presentationFullscreenActive;
    private DateTime _currentCourseDate = DateTime.Today;
    private string _currentDocumentName = string.Empty;
    private string _currentDocumentPath = string.Empty;
    private int _currentPageIndex = 1;
    private string _currentCacheKey = string.Empty;
    private PresentationType _currentPresentationType = PresentationType.None;

    private bool _photoModeActive;
    private bool _photoUnboundedInkCanvasEnabled;
    private bool _photoInputTelemetryEnabled;
    private bool _photoUseLowQualityScaling;
    private bool _photoFullscreen;
    private bool _photoLoading;
    private CrossPageDisplayUpdateRuntimeState _crossPageDisplayUpdateState = CrossPageDisplayUpdateRuntimeState.Default;
    private CrossPageReplayRuntimeState _crossPageReplayState = CrossPageReplayRuntimeState.Default;
    private CrossPageDisplayUpdateClockState _crossPageDisplayUpdateClockState = CrossPageDisplayUpdateClockState.Default;
    private CrossPageUpdateRequestRuntimeState _crossPageUpdateRequestState = CrossPageUpdateRequestRuntimeState.Default;
    private CrossPageInkVisualSyncRuntimeState _crossPageInkVisualSyncState = CrossPageInkVisualSyncRuntimeState.Default;
    private ScaleTransform _photoPageScale = new ScaleTransform(PhotoTransformViewportDefaults.DefaultScale, PhotoTransformViewportDefaults.DefaultScale);
    private ScaleTransform _photoScale = new ScaleTransform(PhotoTransformViewportDefaults.DefaultScale, PhotoTransformViewportDefaults.DefaultScale);
    private TranslateTransform _photoTranslate = new TranslateTransform(0, 0);
    private TranslateTransform _photoInkPanCompensation = new TranslateTransform(0, 0);
    private Matrix _lastValidPhotoInverseMatrix = Matrix.Identity;
    private double _lastInkRedrawPhotoTranslateX;
    private double _lastInkRedrawPhotoTranslateY;
    private double _lastPhotoInteractiveRefreshTranslateX;
    private double _lastPhotoInteractiveRefreshTranslateY;
    private bool _photoPanning;
    private bool _photoManipulating;
    private bool _photoPanHadEffectiveMovement;
    private bool _photoRightClickPending;
    private WpfPoint _photoRightClickStart;
    private WpfPoint _photoPanStart;
    private double _photoPanOriginX;
    private double _photoPanOriginY;
    private readonly List<PhotoPanVelocitySample> _photoPanVelocitySamples = new(PhotoPanInertiaDefaults.MouseVelocitySampleCapacity);
    private string _photoInertiaProfile = PhotoInertiaProfileDefaults.Standard;
    private PhotoPanInertiaTuning _photoPanInertiaTuning = PhotoPanInertiaTuning.Default;
    private Vector _photoPanInertiaVelocityDipPerMs;
    private DateTime _photoPanInertiaLastTickUtc = PhotoInputConflictDefaults.UnsetTimestampUtc;
    private DateTime _photoPanInertiaStartUtc = PhotoInputConflictDefaults.UnsetTimestampUtc;
    private TimeSpan _photoPanInertiaLastRenderingTime = TimeSpan.MinValue;
    private bool _photoPanInertiaRenderingAttached;
    private bool _photoRestoreFullscreenPending;
    private int _photoFullscreenBoundsToken;
    private bool _photoDocumentIsPdf;
    private PdfDocumentHost? _pdfDocument;
    private int _pdfPageCount;
    private int _lastPdfNavigationDirection;
    private readonly Dictionary<int, BitmapSource> _pdfPageCache = new();
    private readonly LinkedList<int> _pdfPageOrder = new();
    private readonly object _pdfRenderLock = new();
    private int _pdfPrefetchInFlight;
    private int _pdfPrefetchToken;
    private readonly HashSet<int> _pdfPinnedPages = new();
    private int _pdfVisiblePrefetchInFlight;
    private int _pdfVisiblePrefetchToken;
    private int _photoLoadToken;
    private double _photoWheelZoomBase = PhotoWheelZoomBaseDefault;
    private double _photoGestureZoomSensitivity = PhotoZoomInputDefaults.GestureSensitivityDefault;
    private readonly HashSet<string> _neighborInkRenderPending = new(StringComparer.OrdinalIgnoreCase);
    private readonly HashSet<string> _neighborInkSidecarLoadPending = new(StringComparer.OrdinalIgnoreCase);
    private bool _rememberPhotoTransform;
    private bool _photoUserTransformDirty;
    private double _lastPhotoScaleX = PhotoTransformViewportDefaults.DefaultScale;
    private double _lastPhotoScaleY = PhotoTransformViewportDefaults.DefaultScale;
    private double _lastPhotoTranslateX;
    private double _lastPhotoTranslateY;
    private readonly Dictionary<string, PhotoTransformState> _photoPageTransforms = new(StringComparer.OrdinalIgnoreCase);
    private bool _photoUnifiedTransformReady;
    private DispatcherTimer? _photoUnifiedTransformSaveTimer;
    private DispatcherTimer? _photoTransformSaveTimer;
    private bool _photoTransformSavePending;
    private bool _photoTransformSaveUserAdjusted;
    private bool _foregroundPresentationActive;
    private PresentationType _foregroundPresentationType;
    private IntPtr _foregroundPresentationHandle;
    private bool _foregroundPhotoActive;
    private double _pendingUnifiedScaleX;
    private double _pendingUnifiedScaleY;
    private double _pendingUnifiedTranslateX;
    private double _pendingUnifiedTranslateY;

    private bool _crossPageDisplayEnabled;
    private bool _crossPageDragging;
    private bool _crossPageTranslateClamped;
    private bool _crossPageUpdateDeferredByInkInput;
    private int _lastInputSwitchFromPage;
    private int _lastInputSwitchToPage;
    private DateTime _lastInputSwitchUtc = CrossPageRuntimeDefaults.UnsetTimestampUtc;
    private int _photoPostInputRefreshDelayMs = PaintPresetDefaults.PostInputRefreshDefaultMs;
    private DateTime _lastCrossPagePointerUpUtc = CrossPageRuntimeDefaults.UnsetTimestampUtc;
    private int _crossPagePostInputRefreshToken;
    private int _crossPageMissingBitmapRefreshToken;
    private DateTime _lastCrossPageMissingBitmapRefreshUtc = CrossPageRuntimeDefaults.UnsetTimestampUtc;
    private long _crossPagePointerUpSequence;
    private long _crossPagePostInputRefreshAppliedSequence = -1;
    private List<string> _photoSequencePaths = new();
    private int _photoSequenceIndex = -1;
    private readonly Dictionary<int, BitmapSource> _neighborImageCache = new();
    private readonly Dictionary<int, double> _neighborPageHeightCache = new();
    private readonly HashSet<int> _neighborImagePrefetchPending = new();
    private Canvas? _neighborPagesCanvas;
    private readonly List<WpfImage> _neighborPageImages = new();
    private readonly List<WpfImage> _neighborInkImages = new();
    private DateTime _lastNeighborPagesNonEmptyUtc = CrossPageRuntimeDefaults.UnsetTimestampUtc;
    private readonly Dictionary<string, InkBitmapCacheEntry> _neighborInkCache = new(StringComparer.OrdinalIgnoreCase);
    private int _interactiveSwitchPinnedNeighborPage;
    private DateTime _interactiveSwitchPinnedNeighborInkHoldUntilUtc = CrossPageRuntimeDefaults.UnsetTimestampUtc;
    private double _crossPageNormalizedWidthDip;
    private bool _crossPageBoundsCacheValid;
    private bool _crossPageBoundsCacheIncludeSlack;
    private int _crossPageBoundsCacheCurrentPage;
    private int _crossPageBoundsCacheTotalPages;
    private double _crossPageBoundsCacheViewportWidth;
    private double _crossPageBoundsCacheViewportHeight;
    private double _crossPageBoundsCacheNormalizedWidthDip;
    private double _crossPageBoundsCacheScaleX;
    private double _crossPageBoundsCacheScaleY;
    private double _crossPageBoundsCacheMinX;
    private double _crossPageBoundsCacheMaxX;
    private double _crossPageBoundsCacheMinY;
    private double _crossPageBoundsCacheMaxY;
    private DateTime _crossPageBoundsCacheUpdatedUtc = CrossPageRuntimeDefaults.UnsetTimestampUtc;
    private TransformGroup? _photoContentTransform;
    private readonly SessionCoordinator _sessionCoordinator;
    private readonly CancellationTokenSource _overlayLifecycleCancellation = new();
    private readonly ILogger<PaintOverlayWindow>? _logger;
    private int _overlayClosed;

    public event Action<string, DateTime>? InkContextChanged;
    public event Action<bool>? PhotoModeChanged;
    public event Action<int>? PhotoNavigationRequested;
    public event Action<double, double, double, double>? PhotoUnifiedTransformChanged;
    public event Action<FloatingZOrderRequest>? FloatingZOrderRequested;
    public event Action? PresentationFullscreenDetected;
    public event Action<PresentationForegroundSource>? PresentationForegroundDetected;
    public event Action? PhotoForegroundDetected;
    public event Action? PhotoCloseRequested;
    public event Action? PhotoCursorModeFocusRequested;
    public event Action<UiSessionTransition>? UiSessionTransitionOccurred;

    public UiSessionState CurrentSessionState => _sessionCoordinator.CurrentState;
    public IReadOnlyList<string> CurrentSessionViolations => _sessionCoordinator.LastViolations;
}
